<a href="https://colab.research.google.com/github/adibansal06/UCS420_CC_LabAssignments_1024170054/blob/main/Assignment4(NumPy).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

# Q1


In [3]:
arr = np.array([10, 20, 30, 40, 50])

print("Original array:", arr)
print("After adding 2:", arr + 2)
print("After multiplying by 3:", arr * 3)
print("After dividing by 2:", arr / 2)

Original array: [10 20 30 40 50]
After adding 2: [12 22 32 42 52]
After multiplying by 3: [ 30  60  90 120 150]
After dividing by 2: [ 5. 10. 15. 20. 25.]


# Q2 (a)

In [4]:
arr = np.array([1, 2, 3, 6, 4, 5])

print("\nQ2(a)")
print("Original array:", arr)
print("Reversed array:", arr[::-1])


Q2(a)
Original array: [1 2 3 6 4 5]
Reversed array: [5 4 6 3 2 1]


# Q2 (b)

In [5]:
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

print("\nQ2(b)(i)")
x_values, x_counts = np.unique(x, return_counts=True)
most_frequent_x = x_values[np.argmax(x_counts)]
print("Most frequent value:", most_frequent_x)
print("Indices:", np.where(x == most_frequent_x)[0])

print("\nQ2(b)(ii)")
y_values, y_counts = np.unique(y, return_counts=True)
most_frequent_y = y_values[np.argmax(y_counts)]
print("Most frequent value:", most_frequent_y)
print("Indices:", np.where(y == most_frequent_y)[0])


Q2(b)(i)
Most frequent value: 1
Indices: [0 5 7 8 9]

Q2(b)(ii)
Most frequent value: 1
Indices: [0 1 2]


# Q3

In [6]:
arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])

print("\nQ3")
print("1st row, 2nd column:", arr[0, 1])
print("3rd row, 1st column:", arr[2, 0])


Q3
1st row, 2nd column: 20
3rd row, 1st column: 70


# Q4

In [7]:
Aditya_Bansal = np.linspace(10, 100, 25)

print("\nQ4")
print("Array:", Aditya_Bansal)
print("Dimensions:", Aditya_Bansal.ndim)
print("Shape:", Aditya_Bansal.shape)
print("Total elements:", Aditya_Bansal.size)
print("Data type:", Aditya_Bansal.dtype)
print("Total bytes:", Aditya_Bansal.nbytes)

transpose_Aditya_Bansal = Aditya_Bansal.reshape(25, 1)
print("Transpose using reshape():")
print(transpose_Aditya_Bansal)

print("Transpose using T attribute:")
print(Aditya_Bansal.T)

# Yes, T can also be used, but for a 1-D array it does not change its shape.
# reshape(25, 1) converts it into a column array.



Q4
Array: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions: 1
Shape: (25,)
Total elements: 25
Data type: float64
Total bytes: 200
Transpose using reshape():
[[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
Transpose using T attribute:
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


# Q5

In [8]:
ucs420_Aditya_Bansal = np.array([[10, 20, 30, 40],
                                 [50, 60, 70, 80],
                                 [90, 15, 20, 35]])

print("\nQ5")
print("Original array:")
print(ucs420_Aditya_Bansal)

print("Mean:", np.mean(ucs420_Aditya_Bansal))
print("Median:", np.median(ucs420_Aditya_Bansal))
print("Maximum:", np.max(ucs420_Aditya_Bansal))
print("Minimum:", np.min(ucs420_Aditya_Bansal))
print("Unique elements:", np.unique(ucs420_Aditya_Bansal))

reshaped_ucs420_Aditya_Bansal = ucs420_Aditya_Bansal.reshape(4, 3)
print("\nReshaped array (4 x 3):")
print(reshaped_ucs420_Aditya_Bansal)

resized_ucs420_Aditya_Bansal = np.resize(ucs420_Aditya_Bansal, (2, 3))
print("\nResized array (2 x 3):")
print(resized_ucs420_Aditya_Bansal)


Q5
Original array:
[[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]
Mean: 43.333333333333336
Median: 37.5
Maximum: 90
Minimum: 10
Unique elements: [10 15 20 30 35 40 50 60 70 80 90]

Reshaped array (4 x 3):
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]

Resized array (2 x 3):
[[10 20 30]
 [40 50 60]]
